/// Katalog aller Belohnungen fuer Heinz' Toechter.
/// Neues 5-Tier-System mit Sterne-Waehrung.
/// Alle Kosten in Sternen (~10 Sterne pro Lernaufgabe).

import 'reward_shop.dart';

abstract class RewardCatalog {
  RewardCatalog._();

  static const List<RewardItem> all = <RewardItem>[
    // ─────────────────── TIER 1: MICRO (50-250 Sterne) ───────────────────

    RewardItem(
      id: 'sticker_aussuchen',
      title: 'Sticker aussuchen',
      emoji: '🎨',
      description: 'Du darfst dir einen Sticker aus der Schachtel aussuchen.',
      cost: 50,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.micro,
      estimatedTasksNeeded: 5,
    ),
    RewardItem(
      id: 'extra_spielzeit_5min',
      title: '5 Min Extra-Spielzeit',
      emoji: '⏰',
      description: '5 Minuten extra spielen – heute!',
      cost: 75,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.micro,
      estimatedTasksNeeded: 8,
    ),
    RewardItem(
      id: 'lieblingssticker',
      title: 'Lieblingssticker',
      emoji: '⭐',
      description: 'Ein besonderer Sticker als Belohnung.',
      cost: 80,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.micro,
      estimatedTasksNeeded: 8,
    ),
    RewardItem(
      id: 'kleine_suessigkeit',
      title: 'Kleine Süßigkeit',
      emoji: '🍬',
      description: 'Eine Kleinigkeit naschen nach dem Lernen.',
      cost: 100,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.micro,
      estimatedTasksNeeded: 10,
    ),
    RewardItem(
      id: 'gute_nacht_geschichte',
      title: 'Gute-Nacht-Geschichte extra',
      emoji: '📖',
      description: 'Heute Abend eine extra Geschichte zum Einschlafen.',
      cost: 120,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.micro,
      estimatedTasksNeeded: 12,
    ),
    RewardItem(
      id: 'kleine_schokolade',
      title: 'Lieblings-Schoki',
      emoji: '🍫',
      description: 'Eine kleine Lieblingsschokolade.',
      cost: 150,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.micro,
      estimatedTasksNeeded: 15,
    ),
    RewardItem(
      id: 'extra_spielplatz',
      title: 'Spielplatz extra',
      emoji: '🎠',
      description: 'Heute noch einmal extra auf den Spielplatz.',
      cost: 200,
      currency: RewardCurrency.stars,
      seasons: <Season>[Season.spring, Season.summer, Season.autumn],
      tier: RewardTier.micro,
      estimatedTasksNeeded: 20,
    ),
    RewardItem(
      id: '5min_laenger_aufbleiben',
      title: '5 Minuten länger aufbleiben',
      emoji: '🌙',
      description: 'Heute Abend 5 Minuten später ins Bett.',
      cost: 200,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.micro,
      estimatedTasksNeeded: 20,
    ),
    RewardItem(
      id: 'lieblingsjause',
      title: 'Lieblingsjause aussuchen',
      emoji: '🥪',
      description: 'Du darfst heute deine Lieblingsjause aussuchen.',
      cost: 250,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.micro,
      estimatedTasksNeeded: 25,
    ),

    // ─────────────────── TIER 2: SMALL (300-800 Sterne) ───────────────────

    RewardItem(
      id: 'gemeinsam_malen',
      title: 'Gemeinsam malen',
      emoji: '🎨',
      description: 'Zusammen mit Mama oder Papa malen und basteln.',
      cost: 300,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.small,
      estimatedTasksNeeded: 30,
    ),
    RewardItem(
      id: 'kleines_basteln',
      title: 'Kleines Basteln',
      emoji: '✂️',
      description: 'Ein kleines Bastelprojekt gemeinsam machen.',
      cost: 350,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.small,
      estimatedTasksNeeded: 35,
    ),
    RewardItem(
      id: 'essen_aussuchen',
      title: 'Lieblingsessen aussuchen',
      emoji: '🍝',
      description: 'Du darfst heute das Mittagessen oder Abendessen bestimmen.',
      cost: 400,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.small,
      estimatedTasksNeeded: 40,
    ),
    RewardItem(
      id: 'extra_10min',
      title: '10 Min Extra-Zeit',
      emoji: '⏰',
      description: '10 Minuten extra – Spielen, Fernsehen oder Tablet.',
      cost: 450,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.small,
      estimatedTasksNeeded: 45,
    ),
    RewardItem(
      id: 'lieblings_film',
      title: 'Lieblingsfilm',
      emoji: '🎬',
      description: 'Du darfst deinen Lieblingsfilm für den Familienabend aussuchen.',
      cost: 600,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.small,
      estimatedTasksNeeded: 60,
    ),
    RewardItem(
      id: 'spielplatz_gross',
      title: 'Langer Spielplatztag',
      emoji: '🎠',
      description: 'Ein langer Nachmittag am großen Spielplatz.',
      cost: 700,
      currency: RewardCurrency.stars,
      seasons: <Season>[Season.spring, Season.summer, Season.autumn],
      tier: RewardTier.small,
      estimatedTasksNeeded: 70,
    ),

    // ─────────────────── TIER 3: MEDIUM (1000-3000 Sterne) ───────────────────

    RewardItem(
      id: 'pizzaabend',
      title: 'Pizzaabend',
      emoji: '🍕',
      description: 'Ein gemütlicher Pizzaabend – du suchst den Belag aus!',
      cost: 1000,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.medium,
      estimatedTasksNeeded: 100,
    ),
    RewardItem(
      id: 'kinoabend_zuhause',
      title: 'Kinoabend zuhause',
      emoji: '🎬',
      description: 'Kino-Feeling zuhause – Film aussuchen, Popcorn machen!',
      cost: 1200,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.medium,
      estimatedTasksNeeded: 120,
    ),
    RewardItem(
      id: 'kleines_buch',
      title: 'Kleines Buch aussuchen',
      emoji: '📚',
      description: 'Ein Buch aus der Bücherei oder Buchhandlung selbst aussuchen.',
      cost: 1500,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.medium,
      estimatedTasksNeeded: 150,
    ),
    RewardItem(
      id: 'bastelset',
      title: 'Bastelset',
      emoji: '✂️',
      description: 'Ein kleines Bastelset aus dem Geschäft aussuchen.',
      cost: 1800,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.medium,
      estimatedTasksNeeded: 180,
    ),
    RewardItem(
      id: 'schwimmen_gehen',
      title: 'Schwimmen gehen',
      emoji: '🏊',
      description: 'Ausflug zum Freibad oder Badesee.',
      cost: 2000,
      currency: RewardCurrency.stars,
      seasons: <Season>[Season.spring, Season.summer],
      tier: RewardTier.medium,
      estimatedTasksNeeded: 200,
    ),
    RewardItem(
      id: 'eis_essen_gehen',
      title: 'Eis essen gehen',
      emoji: '🍦',
      description: 'Großer Eisbecher beim Lieblings-Eissalon.',
      cost: 2500,
      currency: RewardCurrency.stars,
      seasons: <Season>[Season.spring, Season.summer],
      tier: RewardTier.medium,
      estimatedTasksNeeded: 250,
    ),

    // ─────────────────── TIER 4: BIG (5000-12000 Sterne) ───────────────────

    RewardItem(
      id: 'tiergarten',
      title: 'Tiergarten-Besuch',
      emoji: '🦓',
      description: 'Schönbrunn Tiergarten – ein ganzer Tag mit Mama und Papa.',
      cost: 5000,
      currency: RewardCurrency.stars,
      seasons: <Season>[Season.spring, Season.summer, Season.autumn],
      tier: RewardTier.big,
      parentApprovalRequired: true,
      estimatedTasksNeeded: 500,
    ),
    RewardItem(
      id: 'kino_ausflug',
      title: 'Kino-Ausflug',
      emoji: '🎥',
      description: 'Einen Kinderfilm im echten Kino schauen mit Popcorn.',
      cost: 6000,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.big,
      parentApprovalRequired: true,
      estimatedTasksNeeded: 600,
    ),
    RewardItem(
      id: 'erlebnisbad',
      title: 'Erlebnisbad-Tag',
      emoji: '🏊',
      description: 'Ein ganzer Tag im Erlebnisbad mit Rutschen und Wellen.',
      cost: 7000,
      currency: RewardCurrency.stars,
      seasons: <Season>[Season.spring, Season.summer],
      tier: RewardTier.big,
      parentApprovalRequired: true,
      estimatedTasksNeeded: 700,
    ),
    RewardItem(
      id: 'papa_ausflug',
      title: 'Papa-Tochter-Ausflug',
      emoji: '👨‍👧',
      description: 'Ein besonderer Ausflug nur mit Papa – wohin du möchtest!',
      cost: 8000,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.big,
      parentApprovalRequired: true,
      estimatedTasksNeeded: 800,
    ),
    RewardItem(
      id: 'mama_ausflug',
      title: 'Mama-Tochter-Ausflug',
      emoji: '👩‍👧',
      description: 'Ein besonderer Ausflug nur mit Mama – wohin du möchtest!',
      cost: 8000,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.big,
      parentApprovalRequired: true,
      estimatedTasksNeeded: 800,
    ),
    RewardItem(
      id: 'grosses_spielzeug',
      title: 'Größeres Spielzeug',
      emoji: '🧸',
      description: 'Ein etwas größeres Spielzeug aus dem Spielzeugladen aussuchen.',
      cost: 10000,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.big,
      parentApprovalRequired: true,
      estimatedTasksNeeded: 1000,
    ),
    RewardItem(
      id: 'lego_set',
      title: 'Lego-Set',
      emoji: '��',
      description: 'Ein eigenes Lego-Set zum Bauen aussuchen.',
      cost: 12000,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.big,
      parentApprovalRequired: true,
      estimatedTasksNeeded: 1200,
    ),

    // ─────────────────── TIER 5: PREMIUM (20000+ Sterne) ───────────────────

    RewardItem(
      id: 'besonderer_familientag',
      title: 'Besonderer Familientag',
      emoji: '🌟',
      description: 'Ein ganz besonderer Familientag – ihr plant ihn gemeinsam!',
      cost: 20000,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.premium,
      parentApprovalRequired: true,
      isPremiumReward: true,
      estimatedTasksNeeded: 2000,
    ),
    RewardItem(
      id: 'lego_gross',
      title: 'Großes Lego-Set',
      emoji: '🧱',
      description: 'Ein großes Lego-Set (z.B. Schloss oder Raumschiff) – ein Mega-Geschenk!',
      cost: 22000,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.premium,
      parentApprovalRequired: true,
      isPremiumReward: true,
      estimatedTasksNeeded: 2200,
    ),
    RewardItem(
      id: 'grosser_ausflug',
      title: 'Großer Ausflug',
      emoji: '🗺️',
      description: 'Ein großer Familienausflug – ihr sucht gemeinsam das Ziel aus!',
      cost: 25000,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.premium,
      parentApprovalRequired: true,
      isPremiumReward: true,
      estimatedTasksNeeded: 2500,
    ),
    RewardItem(
      id: 'family_park',
      title: 'Family Park',
      emoji: '🎢',
      description: 'Ein ganzer Tag im Family Park – das ultimative Abenteuer!',
      cost: 30000,
      currency: RewardCurrency.stars,
      seasons: <Season>[Season.spring, Season.summer, Season.autumn],
      tier: RewardTier.premium,
      parentApprovalRequired: true,
      isPremiumReward: true,
      estimatedTasksNeeded: 3000,
    ),
    RewardItem(
      id: 'grosser_erlebnisgutschein',
      title: 'Großer Erlebnisgutschein',
      emoji: '🎁',
      description: 'Ein großer Erlebnis-Gutschein – ihr entscheidet gemeinsam was!',
      cost: 35000,
      currency: RewardCurrency.stars,
      seasons: <Season>[],
      tier: RewardTier.premium,
      parentApprovalRequired: true,
      isPremiumReward: true,
      estimatedTasksNeeded: 3500,
    ),
  ];
}
